### PR TITLE
removing shml from context

### PR DESCRIPTION
**Pull request by jmervine**
1. I'm removing [`shml`](https://github.com/MaxCDN/shml) from `shunt` itself, but allowing it to be sourced when available. This address [this shml bug](https://github.com/MaxCDN/shml/issues/22).
2. Adding travis support.

cc: @jdorfman 

Note: This merge should be included as a versioned (tagged) release.

### CODE REVIEW

**Comment by jmervine** [comment]
@jdorfman I'll merge, tag and release on your ":+1:"

**Comment by jdorfman** [comment]
we need color

**Comment by jmervine** [comment]
@jdorfman we have color

**Comment by jmervine** [comment]
@jdorfman color / icons are still there (https://github.com/odb/shunt/pull/19/files#diff-191e28e524e7b6105c3816c0120e71d7R190) just no longer from shml.

**Comment by jdorfman** [comment]
ohhhhh.  My bad!  :+1:

**Comment by jmervine** [comment]
@jdorfman Going to merge and release this, but open an issue to look at better ways of using `shml` for future versions.

**Pull request merged**
